# Generated by Django 3.2.2 on 2021-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('1', 'о любви'), ('2', 'о войне'), ('1', 'о природе'), ('2', 'для детей'), ('1', 'о Родине'), ('2', 'о жизни'), ('1', 'о смерти'), ('2', 'о себе')], max_length=60, verbose_name='Категории'),
        ),
    ]
