# Generated by Django 3.2.2 on 2021-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='value',
        ),
        migrations.AddField(
            model_name='follower',
            name='is_reader',
            field=models.BooleanField(default=True, verbose_name='Значение'),
        ),
    ]
