# Generated by Django 3.2.2 on 2021-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0002_auto_20210726_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.RemoveField(
            model_name='verse',
            name='views',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to='verse.Author'),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
