# Generated by Django 3.2.2 on 2021-07-25 13:43

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0002_comment_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=333, verbose_name='Содержание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=utils.upload.upload_instance, verbose_name='Изображение')),
                ('main_page_filter', models.BooleanField(default=False, verbose_name='Рекомендация новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
