# Generated by Django 3.2.2 on 2021-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=333, verbose_name='Содержание'),
        ),
    ]
