# Generated by Django 3.2.2 on 2021-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=True, verbose_name='Лайки'),
        ),
    ]
